### ISSUE TITLE
[SECURITY] API token is published

### ISSUE THREAD

**Issue by jhpratt** [risoflora/wethr#5]
API tokens should never be committed. They should be stored in environment variables or a configuration file that is in `.gitignore`.

**Comment by silvioprog** [comment]
@jhpratt hmm, do you mean [src/consts.rs#L5](https://github.com/risoflora/wethr/blob/master/src/consts.rs#L5)? If so, it is public: [twobucks/wethr/wethr.js#L7](https://github.com/twobucks/wethr/blob/master/wethr.js#L7).

**Comment by jhpratt** [comment]
Yes, that is what I was referring to. Seems odd that they would have a public API key, but okay 🙂 It's their problem, not yours.

**Comment by silvioprog** [comment]
Anyway, it should be configured too, assuming this default one if not informed. I'm going to add it to the [wish list](https://github.com/risoflora/wethr#whish-list). Thanks for reporting! :smiley:

**Comment by silvioprog** [comment]
@jhpratt done: [#wish-list](https://github.com/risoflora/wethr#wish-list) :+1:
